
voice_output = {
            "greet_info": "yeah ! I'm actually, calling on behalf of an independent and financial advisory firm regarding Careshield life. So currently we are actually spreading awareness regarding government disability income scheme. So just want to have quick check on are you aware of it?",
            "info": "Yup,Basically Careshield life is a government initiative that provides long-term care insurance scheme giving basic financial support to singaporeans so should any Singaporeans become severely disabled and need medical care for a prolonged duration this free upgrade service will enhance the payout. So just want to check would you be interested to find out more?",
            "offers_info": "Yeah,so it is a national long term care insurance scheme. offers payout upon severe disability",
            "payable_info": "Yeah,so it would be fully payable by Medisave from the age of(30-67) will it be alright if our prfessional agents contact you again to tell you more about this careshieldlife scheme?",
            "language_check": "I am free,I could speak only in english language. May be I would get my human representative agents to give you a call. Thank you ?",
            "call_again_check": "Alright,so sorry to bother you can I give you a call back some time later this week?",
            "sad_bye": "Alright,thanks for picking up the call and so sorry to disturb you.",
            "ebrochure_check": "No problem. Thank you for your time I will send you an e-brochure to you instead. Thank you for your time.",
            "goodbye": "Thank you for your time. Goodbye.",
            "happy_bye": "Oh! that will be great. Thank you so much for your time. I will get my professional agents   ",
            "greet_call_conform": "Hey,Hii. This is Janice calling from Aviva. Are you convenient to speak right now?",
            "upgrade_check": "Yeah,that will be great! So anyway will you be interested in our free upgrade as well? So you don't have worry, because you will not need to pay for anything. As careshieldlife is a disability income scheme launched by government as long as you are unable to move around the house,the government will be giving you money every month. So will you be interested?",
            "reason_check": "oh! why not ?",
            "more_info": "Careshield life is a disability income scheme launched by the government. As long as you are unable to move around the house, the government will be giving you money every month. Will you be interested in this scheme?",
            "out_of_scope": "So sorry, I didn't get what you said. Would you mind rephrasing what you said earlier on.",
            "contact_representative": "Thank you for expressing your interest, we will get our human representative to contact you shortly.",  
            "bye":"Thank you. Bye.", 
            "happy_goodbye":"Thanks for picking up the call our professional agents will call you. Thank you.",
            "contact_agent":"thats great,we will have our professional agents to follow up on this. Thank you.",
        }
